### ISSUE TITLE
A possible explanation for the outliers described in the video

### ISSUE THREAD

**Issue by Ghost---Shadow** [Hvass-Labs/FinanceOps#1]
In the video you mentioned about further exploring the outliers.

`In [26]` plot 10. The outliers in the range 15% to 20% revenue and 1.5 to 3 P/B ratio could be explained by software companies.

Software companies have very little capital intensive assets compared to heavy manufacturing and energy industries. It makes sense that they have a high revenue while maintaining a low P/B ratio.

However I cannot confirm my hypothesis as the ticker symbols are not included in the dataset.

`In [24]` plot 8. The outliers in the range 10%-20% revenue and P/S ratio 1-1.5 might also be the same tech corporations for reasons unknown. (Maybe they are lesser known startups, who are making big bucks but flying under the radar. This hypothesis would be hard to test.)

Could you add the ticker symbol data in the given dataset so that I can proceed with my hypothesis testing?

**Comment by Hvass-Labs** [comment]
Thanks for your input. However, I think you have misunderstood the scatter-plots for the S&P 500. As I said in the video, each dot in a scatter-plot represents the return for the WHOLE S&P 500 over a PERIOD IN TIME - the dots are NOT for different companies, they are for different PERIODS! :-) We are interested in forecasting the future return on the S&P 500 from its P/Sales or P/Book ratio.

You also said:

> Software companies have very little capital intensive assets compared to heavy manufacturing and energy industries. It makes sense that they have a high revenue while maintaining a low P/B ratio.

Actually it is the opposite: High-tech companies typically have very high P/Book ratios because their profits are high but their assets and equity (aka. book-value) are low.

Example: Apple's market-cap is about USD 935 billion, their 2017 sales were USD 229b, net income USD 48b (21% net profit margin), total assets USD 375b, equity USD 134b. This gives P/Sales = 935 / 229 = 4.1 and P/Book = 935 / 134 = 7. Data from: https://finance.yahoo.com/quote/AAPL/balance-sheet?p=AAPL

At the end of fiscal year 2017 Apple had Cash & Equivalents of USD 20b, short-term investments of USD 54b, but also Long-Term Investments of USD 195b - which I suspects are also primarily invested in financial securities such as bonds. But I would have to look in their actual financial reports to understand exactly what those are.

Nevertheless, Apple has excess cash of somewhere between roughly USD 74b and 270b. If a significant part of those were to be paid out as dividends or used as a share buyback then the assets and equity would both decrease accordingly. That would significantly raise the P/Book ratio.

There is a lot of research that could be done in this area and I encourage you to continue. Unfortunately I cannot help you with more data as I am also having big trouble getting data myself. Maybe you can use Quantopian to get data? I haven't tried it myself.
