### ISSUE TITLE
Running the Repository inside a Docker Container

### ISSUE THREAD

**Issue by AmirNaghibi** [Hvass-Labs/FinanceOps#4]
Hi @Hvass-Labs,
Can I add simple docker instructions so users can get up and running quickly? With Docker container, users don't have to install required software such as **python**and **jupyter notebook** since it is already available in docker container.

It is something like this but I can simplify it and **update the readme** with a short section for running the notebooks from the docker container. 
`docker run --rm -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/jovyan/work jupyter/datascience-notebook`

great work by the way! 💯

**Comment by Hvass-Labs** [comment]
Thanks for the suggestion. I prefer to make all changes to this repo myself, so I would need to understand how to do this and why it is useful. I have never used Docker so please elaborate why it would be useful for this project? Wouldn't I need to make a custom Docker container that would include all the requirements for this project? And then I suppose I would have to update the Docker container when I make changes to requirements.txt? Wouldn't it be a lot easier for both me and the user if they just run the Notebooks on Google Colab, if the user doesn't want to install anything? I don't quite see the usefulness of Docker for a project like this? Please explain.

**Comment by magick93** [comment]
Docker offers maximum portability and simplicity. Basically, if you can run docker, with a single command you can run dockerized software. It both abstracts away the idiosyncrasy of setting up the required environment and also ensures a high degree of security.

> Wouldn't I need to make a custom Docker container that would include all the requirements for this project? And then I suppose I would have to update the Docker container when I make changes to requirements.txt? 

Not necessarily. My recommendation is to use [Source-to-Image](https://github.com/openshift/source-to-image).  The benefit of using s2i is best described on https://docs.openshift.com/container-platform/3.5/architecture/core_concepts/builds_and_image_streams.html#source-build
You would be able to make changes to, and build, the docker image using a command similar to `2i build https://github.com/Hvass-Labs/FinanceOps centos/python:3.9 finops`

Of course you - or other contributes - could add a custom dockerfile to build your own image.

**Comment by Hvass-Labs** [comment]
Thanks for the explanation. I'll give it a try as soon as I have the time.

**Comment by Hvass-Labs** [comment]
Several of these Python Notebooks write data to disk (e.g. for saving/loading various data and for writing plots to graphics-files), and some of the Notebooks also use other Python packages that write and read data on disk (e.g. the SimFin package). I have investigated this aspect of Docker a bit more. It appears that writing data to disk from inside Docker containers is quite complicated, because it requires the creation of so-called Docker "volumes" that must be mounted and passed to the Docker container when running it, see [here](https://docs.docker.com/storage/).

The instructions for setting this up for the end-user of this project, would probably become far more complicated than either running these Python Notebooks in a virtual environment, or using Google Colab if people don't want to install anything on their own computer - both these methods are already described in the README.

If I have mis-understood this aspect of Docker, then please explain how to **easily** write/read data on the local disk from inside Docker containers.

Maybe I will update the README with my reason for not having a Docker image.

In my investigation I also found that you can automatically build Docker images using Docker Hub, see [here](https://davelms.medium.com/build-your-docker-images-automatically-when-pushing-new-code-to-github-394f4c1679cc). That is actually pretty cool! But again, because some of these Notebooks need data i/o on the local disk, I think Docker is too complicated.

But thanks for the suggestion!

**Comment by Hvass-Labs** [comment]
Oops, I just now see that the installation instructions in the README are outdated. They are missing instructions on how to create a virtual environment and install all the dependencies. I will update the README soon and hopefully that will make it easy enough to run these Notebooks without using Docker.
